package fr.gestionStock.persistance.entities;
// Generated 13 avr. 2021 � 15:21:25 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "PRODUIT", schema = "GESTIONSTOCK")
public class Produit implements java.io.Serializable {

	private BigDecimal idproduit;
	private Categorie categorie=new Categorie();
	private String desigproduit;
	private Double puproduit;
	private BigDecimal qteproduit;
	private String configproduit;
	private String marqueproduit;
	private String modeleproduit;
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Produit() {
	}

	public Produit(BigDecimal idproduit) {
		this.idproduit = idproduit;
	}

	public Produit(BigDecimal idproduit, Categorie categorie, String desigproduit, Double puproduit,
			BigDecimal qteproduit, String configproduit, String marqueproduit, String modeleproduit,
			Set<Commande> commandes) {
		this.idproduit = idproduit;
		this.categorie = categorie;
		this.desigproduit = desigproduit;
		this.puproduit = puproduit;
		this.qteproduit = qteproduit;
		this.configproduit = configproduit;
		this.marqueproduit = marqueproduit;
		this.modeleproduit = modeleproduit;
		this.commandes = commandes;
	}

	@Id

	@Column(name = "IDPRODUIT", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(BigDecimal idproduit) {
		this.idproduit = idproduit;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IDCATEGORIE")
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "DESIGPRODUIT", length = 20)
	public String getDesigproduit() {
		return this.desigproduit;
	}

	public void setDesigproduit(String desigproduit) {
		this.desigproduit = desigproduit;
	}

	@Column(name = "PUPRODUIT", precision = 126, scale = 0)
	public Double getPuproduit() {
		return this.puproduit;
	}

	public void setPuproduit(Double puproduit) {
		this.puproduit = puproduit;
	}

	@Column(name = "QTEPRODUIT", precision = 22, scale = 0)
	public BigDecimal getQteproduit() {
		return this.qteproduit;
	}

	public void setQteproduit(BigDecimal qteproduit) {
		this.qteproduit = qteproduit;
	}

	@Column(name = "CONFIGPRODUIT", length = 20)
	public String getConfigproduit() {
		return this.configproduit;
	}

	public void setConfigproduit(String configproduit) {
		this.configproduit = configproduit;
	}

	@Column(name = "MARQUEPRODUIT", length = 20)
	public String getMarqueproduit() {
		return this.marqueproduit;
	}

	public void setMarqueproduit(String marqueproduit) {
		this.marqueproduit = marqueproduit;
	}

	@Column(name = "MODELEPRODUIT", length = 20)
	public String getModeleproduit() {
		return this.modeleproduit;
	}

	public void setModeleproduit(String modeleproduit) {
		this.modeleproduit = modeleproduit;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "produit")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
